version: '3.8'

services: 
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    depends_on:
      - redis
    build: 
      context: ./project #should be path to the Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=0
      - SECRET_KEY=django-insecure-v^#&gf)$6!twqn1x)-pxj9bverarhlu)wyccvl!*m*-s+n!(y*
      - ALLOWED_HOSTS=localhost, 127.0.0.1
      - DOCKER_MODE=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    container_name: celery
    depends_on:
      - redis
    build: 
      context: ./project
    command: celery --app=project worker -l INFO # ["executable", "arg"]
    volumes:
      - ./project:/usr/src/app/
    environment:
      - DEBUG=0
      - SECRET_KEY=django-insecure-v^#&gf)$6!twqn1x)-pxj9bverarhlu)wyccvl!*m*-s+n!(y*
      - ALLOWED_HOSTS=localhost, 127.0.0.1
      - DOCKER_MODE=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
