version: '3.8'

services: 
  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379" # Expose Redis port to the host machine

  django:
    container_name: django
    depends_on:
      - redis
    build: 
      context: ./project #should be path to the Dockerfile
    # command: uvicorn project.asgi:application --port 8000 --workers 4 --log-level debug --reload
    command: uvicorn project.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=0
      - SECRET_KEY=django-insecure-v^#&gf)$6!twqn1x)-pxj9bverarhlu)wyccvl!*m*-s+n!(y*
      - ALLOWED_HOSTS=localhost, 127.0.0.1
      - DOCKER_MODE=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  celery:
    container_name: celery
    restart: always
    depends_on:
      - redis
    build: 
      context: ./project
    command: celery --app=project worker -l INFO -B # ["executable", "arg"]
    volumes:
      - ./project:/usr/src/app/
    environment:
      - DEBUG=0
      - SECRET_KEY=django-insecure-v^#&gf)$6!twqn1x)-pxj9bverarhlu)wyccvl!*m*-s+n!(y*
      - ALLOWED_HOSTS=localhost, 127.0.0.1
      - DOCKER_MODE=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # env_file:
      #- ./env_vars_django.txt
